### ISSUE TITLE
Using discord-haskell-1.12.0 I get parsing errors for certain type of messages. 

### ISSUE THREAD

**Issue by XanderDJ** [aquarial/discord-haskell#105]
`"gateway - received parse Error - Error in $: Error in $.components[0]: key \"label\" not found while decoding {\"t\":\"MESSAGE_CREATE\",\"s\":22,\"op\":0,\"d\":{\"type\":0,\"tts\":false,\"timestamp\":\"2022-02-28T21:36:26.975000+00:00\",\"referenced_message\":null,\"pinned\":false,\"mentions\":[],\"mention_roles\":[],\"mention_everyone\":false,\"member\":{\"roles\":[\"907349341046439987\"],\"mute\":false,\"joined_at\":\"2021-11-08T19:22:20.669000+00:00\",\"hoisted_role\":null,\"deaf\":false},\"id\":\"947970530764537856\",\"flags\":0,\"embeds\":[{\"type\":\"rich\",\"title\":\"Your pok\233dex\",\"footer\":{\"text\":\"Showing 1\8211\&20 out of 898.\"},\"fields\":[{\"value\":\"<:_:725819513358254101> 14 caught!\",\"name\":\"<:_:721473923262447686> Bulbasaur #1\",\"inline\":true},{\"value\":\"<:_:725819513358254101> 15 caught!\",\"name\":\"<:_:721473923103064096> Ivysaur #2\",\"inline\":true},{\"value\":\"<:_:725819513358254101> 1 caught!\",\"name\":\"<:_:721473923006464001> Venusaur #3\",\"inline\":true},{\"value\":\"<:_:725819513358254101> 11 caught!\",\"name\":\"<:_:721473923153264667> Charmander #4\",\"inline\":true},{\"value\":\"<:_:725819513358254101> 10 caught!\",\"name\":\"<:_:721473923279093860> Charmeleon #5\",\"inline\":true},{\"value\":\"<:_:725819513358254101> 3 caught!\",\"name\":\"<:_:721473923308584990> Charizard #6\",\"inline\":true},{\"value\":\"<:_:725819513358254101> 16 caught!\",\"name\":\"<:_:721473923291545660> Squirtle #7\",\"inline\":true},{\"value\":\"<:_:725819513358254101> 5 caught!\",\"name\":\"<:_:721473923287482458> Wartortle #8\",\"inline\":true},{\"value\":\"<:_:725819513358254101> 3 caught!\",\"name\":\"<:_:721473923270574223> Blastoise #9\",\"inline\":true},{\"value\":\"<:_:725819513358254101> 57 caught!\",\"name\":\"<:_:721473923270705174> Caterpie #10\",\"inline\":true},{\"value\":\"<:_:725819513358254101> 14 caught!\",\"name\":\"<:_:721473923039887484> Metapod #11\",\"inline\":true},{\"value\":\"<:_:725819513358254101> 2 caught!\",\"name\":\"<:_:721473923300196372> Butterfree #1Ending
2\",\"inline\":true},{\"value\":\"<:_:725819513358254101> 58 caught!\",\"name\":\"<:_:721473923060858911> Weedle #13\",\"inline\":true},{\"value\":\"<:_:725819513358254101> 11 caught!\",\"name\":\"<:_:721473923262447716> Kakuna #14\",\"inline\":true},{\"value\":\"<:_:725819513358254101> 6 caught!\",\"name\":\"<:_:721473923316711484> Beedrill #15\",\"inline\":true},{\"value\":\"<:_:725819513358254101> 45 caught!\",\"name\":\"<:_:721473923275030608> Pidgey #16\",\"inline\":true},{\"value\":\"<:_:725819513358254101> 9 caught!\",\"name\":\"<:_:721473923287613501> Pidgeotto #17\",\"inline\":true},{\"value\":\"<:_:725819513358254101> 2 caught!\",\"name\":\"<:_:721473923304128583> Pidgeot #18\",\"inline\":true},{\"value\":\"<:_:725819513358254101> 18 caught!\",\"name\":\"<:_:721473922960326740> Rattata #19\",\"inline\":true},{\"value\":\"<:_:725819513358254101> 10 caught!\",\"name\":\"<:_:721473923035824139> Raticate #20\",\"inline\":true},{\"value\":\"\8206\",\"name\":\"\8206\",\"inline\":true}],\"description\":\"You've caught 800 out of 898 pok\233mon!\",\"color\":16685769}],\"edited_timestamp\":null,\"content\":\"\",\"components\":[{\"type\":1,\"components\":[{\"type\":2,\"style\":2,\"emoji\":{\"name\":\"\9664\65039\"},\"custom_id\":\"589c83d78a1a3bbac94a368bfa247290\"},{\"type\":2,\"style\":2,\"emoji\":{\"name\":\"\9654\65039\"},\"custom_id\":\"ae2071bb587435e9d5921a10d66eec73\"}]}],\"channel_id\":\"907349496546082886\",\"author\":{\"username\":\"Pok\233two\",\"public_flags\":65536,\"id\":\"716390085896962058\",\"discriminator\":\"8236\",\"bot\":true,\"avatar\":\"2489a9b2c2eb951ed908be416ced10a2\"},\"attachments\":[],\"guild_id\":\"504106778246512640\"}}"`

This is the error that I get. Shortened one :GatewayExceptionEventParseError "Error in $: Error in $.components[0]: key \"label\" not found" "Normal event loop". It happens regularly and seems to be linked to a poketwo bot.

**Comment by aquarial** [comment]
Oh yep. Library error. Thanks for the detailed report!

Docs say `label` field is optional <https://discord.com/developers/docs/interactions/message-components#button-object-button-structure>

But the parser requires it. <https://github.com/aquarial/discord-haskell/blob/master/src/Discord/Internal/Types/Components.hs#L102>. 

Only shows up for bots (like poketwo apparently) that don't provide a label. Will get this fixed

**Comment by aquarial** [comment]
1.12.1 should fix this.

**Comment by XanderDJ** [comment]
Thank you for the quick response! Successfully changed to version 1.12.0, excited about threads api.
