### ISSUE TITLE
EditMessage is Outdated

### ISSUE THREAD

**Issue by XanderDJ** [aquarial/discord-haskell#106]
With the new MessageDetailedOpts you can add stuff like actionrowcomponents following the api of discord. But this functionality isn't present in the EditMessage Channel Request. It's not possible to speciffy what you want to do for components in that end point. While this should be possible discord wise I think. Current endpoint
![image](https://user-images.githubusercontent.com/26298748/156455399-663e5993-b273-46cc-93bb-bd429b03bc38.png)

CreateEmbed specifies no fields for components like the MessageDetailedOpts does:
![image](https://user-images.githubusercontent.com/26298748/156455572-64f9e695-3e87-4245-bf5d-b3c629768f32.png)

When handling the code itself it's using a field in JSON that will be deprecated in the future namely _embed_ instead of embeds.

Edit endpoint according to discord docs:
![image](https://user-images.githubusercontent.com/26298748/156456096-baeff4b2-b7c0-4f33-bef5-9f5e2bb9e01f.png)
It has the components attributes.

**Comment by aquarial** [comment]
Should be fixed by https://github.com/aquarial/discord-haskell/pull/107, pushed int 1.12.2
