### ISSUE TITLE
Error when parsing message create

### ISSUE THREAD

**Issue by XanderDJ** [aquarial/discord-haskell#108]
`"gateway - received parse Error - Error in $: Error in $.flags: could not get message flags while decoding {\"t\":\"MESSAGE_CREATE\",\"s\":416,\"op\":0,\"d\":{\"type\":0,\"tts\":false,\"timestamp\":\"2022-03-04T23:13:26.321000+00:00\",\"referenced_message\":null,\"pinned\":false,\"nonce\":\"949444490039394304\",\"mentions\":[],\"mention_roles\":[],\"mention_everyone\":false,\"member\":{\"roles\":[\"771416042076897280\",\"786676037097881600\",\"795129103518269472\",\"826842903103275009\",\"724772592803905637\",\"724407917154926663\",\"740040665785696367\",\"783883468936446003\",\"832840598637248532\",\"855869682187501598\",\"828775645814456382\",\"747260224213352540\",\"724407881004482590\"],\"nick\":\"Stel :)\",\"mute\":false,\"joined_at\":\"2020-09-09T21:01:23.878000+00:00\",\"hoisted_role\":null,\"deaf\":false},\"id\":\"949444490333143091\",\"flags\":1024,\"embeds\":[{\"video\":{\"width\":300,\"url\":\"https://player.twitch.tv/?channel=stelios__&player=facebook&autoplay=true&parent=meta.tag\",\"height\":300},\"url\":\"https://twitch.tv/stelios__\",\"type\":\"video\",\"title\":\"Stelios__ - Twitch\",\"thumbnail\":{\"width\":300,\"url\":\"https://static-cdn.jtvnw.net/jtv_user_pictures/c3e53926-081f-4aa8-bef7-e827b74308b8-profile_image-300x300.png\",\"proxy_url\":\"https://images-ext-2.discordapp.net/external/f9iU-dArfCMOpwlH6E6AI1MVyhwSF4VXk6i5mDEkLvw/https/static-cdn.jtvnw.net/jtv_user_pictures/c3e53926-081f-4aa8-bef7-e827b74308b8-profile_image-300x300.png\",\"height\":300},\"provider\":{\"name\":\"Twitch\"},\"description\":\"Kirby is a Fantasy game, right? | Fantasy Friday! FF5 later! | !qod !waddap !discord !streambeats\"}],\"edited_timestamp\":null,\"content\":\"**Playing the Kirby Demo for a bit to kick off today!**\\n\\nHappy Friday! We'll get to the fantasy bit later on but wanted to start the Kirby demo before we switch over to more Final Fantasy V!\\n\\nAsk me about the question of the day! \128064 \\n\\nhttps://twitch.tv/stelios__\",\"components\":[],\"channel_id\":\"839139461316739082\",\"author\":{\"username\":\"Stelios\",\"public_flags\":512,\"id\":\"90629452878352384\",\"discriminator\":\"9062\",\"avatar\":\"46ad31198db4c8b5e65832b7a3dd5856\"},\"attachments\":[],\"guild_id\":\"723928332269518929\"}}"
`

Shortened error =  GatewayExceptionEventParseError "Error in $: Error in $.flags: could not get message flags" "Normal event loop"

Have got this error multiple times in a row now.

**Comment by aquarial** [comment]
release 1.12.3 which fixes this specific crash. 

There's been more crashes recently due to type errors. This was sort of an intentional feature a while back, but now it's getting annoying. Going to work on https://github.com/aquarial/discord-haskell/blob/master/docs/todo.md#error-handling

**Comment by aquarial** [comment]
Closing this because the issue should be resolved, open a new issue if something goes wrong.
