### ISSUE TITLE
upgrade to lts-13.8

### ISSUE THREAD

**Issue by witoldsz** [aquarial/discord-haskell#12]
I am using `lts-13.8` and cannot add this lib as a dependency _as is_, so have forked and upgraded to lts-13.8 [(pull-req)](https://github.com/witoldsz/discord-haskell/pull/1). Is it possible for `discord-haskell` to support both: `lts-12.10` and `13.8` (possibly others) snapshots?

**Comment by aquarial** [comment]
`master` branch is compatible with 13.8 now.

I had strict version bounds to a specific lts version because it's easier to develop with. I've loosened the bounds to be compatible with multiple snapshots (12.10 up to 13.9). I'll get travis to test these soon.
