### ISSUE TITLE
Requests missing in Webhook Rest API

### ISSUE THREAD

**Issue by Annwan** [aquarial/discord-haskell#122]
In addition to the "Stack compatible webhook and GitHub compatible webhooks mentioned in #4. there is also
- [Edit Webhook Message](https://discord.com/developers/docs/resources/webhook#edit-webhook-message)
- [Delete Webhook Message](https://discord.com/developers/docs/resources/webhook#edit-webhook-message)

**Comment by L0neGamer** [comment]
As discussed on discord, we're not going to support the slack and github webhooks.
