### ISSUE TITLE
Please upgrade to req 2.1

### ISSUE THREAD

**Issue by danwdart** [aquarial/discord-haskell#22]
Everything else used in a project uses req 2.1 - could this be upgraded to use 2.1?

Ta

**Comment by aquarial** [comment]
Increased req from `>=1.1.0 && <1.3` to `>=2.1.0 && <2.2` with commit https://github.com/aquarial/discord-haskell/commit/1cc30454902dac51af654c8aac378f7f980395e5. The only breaking change was req removed `data-default`. 

I also increased the discord-haskell stack lts from 12.10 to 14.4. Still possible to use discord-haskell with lower lts versions, but it will require some more entries in extra-deps.

Tested locally, waiting for travis build https://travis-ci.org/aquarial/discord-haskell/builds/580402390

**Comment by danwdart** [comment]
Amazing. Fastest response I've ever gotten. Looks like Travis likes it. Maybe you want to add GHC 8.6.5 to Travis?

**Comment by danwdart** [comment]
Hmm, what's the release for this?

**Comment by aquarial** [comment]
Oh yeah. I pushed the commit but didn't push a release. Will do.

If you're using stack you can always use a github commit https://github.com/aquarial/discord-haskell/wiki/Installing-the-Library#stack---github

**Comment by danwdart** [comment]
Ah yes - I figured - that's what I was using so far. Thanks!
