### ISSUE TITLE
Voice streaming

### ISSUE THREAD

**Issue by MDeltaX** [aquarial/discord-haskell#26]
Is there any example or guideline of how to stream from & to voice channels?

**Comment by MDeltaX** [comment]
Also it would be great for me to know if you can recommend a way to use this library with normal discord user accounts (for setting custom status etc.)

**Comment by aquarial** [comment]
discord-haskell can't do either of those right now tbh.

Cant do audio/voice and can't login with a user authentication. I'll make a note of limitations in the readme

**Comment by MDeltaX** [comment]
I'm aware of that, but I'd like to have those abilites in haskell and assumed have already experimented with some them, can you outline what I would have to do to implement them / things to avoid that you've already tried? i have no experience with neither discord api nor oauth.

**Comment by aquarial** [comment]
Ah sorry. I haven't looked into them at all. 

You may have already encountered them, but if you are looking to get started the discord api docs are helpful: [voice connections](https://discordapp.com/developers/docs/topics/voice-connections) and [oauth](https://discordapp.com/developers/docs/topics/oauth2).

**Comment by MDeltaX** [comment]
Thanks and no problem. Apart from that is this library awesome!

**Comment by aquarial** [comment]
Update: https://github.com/yutotakano/discord-haskell-voice is working voice API compatible with discord-haskell,
