### ISSUE TITLE
Use monad transformers

### ISSUE THREAD

**Issue by lambdadog** [aquarial/discord-haskell#34]
It's sensible to use a `ReaderT DiscordHandle IO` monad stack instead of just `IO` in many places in this library to avoid passing around the `DiscordHandle` everywhere.

Currently in my application I've got a module specifically dedicated to wrapping this library to use this monad transformer stack and I'd love a future where the `discord-haskell` library itself contained this code so my application didn't have to.

**Comment by aquarial** [comment]
Makes sense. I haven't added monad transformers to this repo mostly because I don't have a solid grasp of them yet. I'll try it out

**Comment by transitracer** [comment]
Here's my current code wrapping it, if it will help:

https://gist.github.com/transitracer/19df568e8bb78b8ee8251ed0773e71c8

**Comment by georgefst** [comment]
@lambdadog Has that code moved? I was just about to reimplement the same thing...

**Comment by lambdadog** [comment]
@georgefst Changed my name! Sorry about that.

https://gist.github.com/lambdadog/19df568e8bb78b8ee8251ed0773e71c8

**Comment by georgefst** [comment]
@lambdadog Thanks!

**Comment by elikoga** [comment]
Can be closed. Due to #51
