### ISSUE TITLE
Crash After Connecting

### ISSUE THREAD

**Issue by pnotequalnp** [aquarial/discord-haskell#40]
It's working fine on my (small) server, but after connecting to a larger server, it crashes with `GatewayExceptionEventParseError "Error in $: Error in $.channels[31]: Unknown channel type:5" "Normal event loop"`

Here's the minimal example I observe the behavior with.
 ```haskell
import Data.Text ( Text )
import qualified Data.Text.IO as T

import Discord
import Discord.Types

test :: Text -> IO ()
test secret = do
  userFacingError <- runDiscord def
    { discordToken   = secret
    , discordOnStart = const $ putStrLn "Connected"
    , discordOnEnd   = putStrLn "Disconnected"
    }
  T.putStrLn userFacingError
```

**Comment by aquarial** [comment]
Hmm. That error is going to be thrown from [the gateway here](https://github.com/aquarial/discord-haskell/blob/master/src/Discord/Internal/Gateway/EventLoop.hs#L198), which will get the ParseError from [getPayload here](https://github.com/aquarial/discord-haskell/blob/master/src/Discord/Internal/Gateway/EventLoop.hs#L127). 

`Unknown channel type:5` is the issue. [discord-haskell only handles types 0-4 right now](https://github.com/aquarial/discord-haskell/blob/master/src/Discord/Internal/Types/Channel.hs#L91), but [discord has added 5 and 6](https://discord.com/developers/docs/resources/channel#channel-object-channel-types). I'll add those and push 1.6.0

**Comment by aquarial** [comment]
Uploaded just now. Should be available in a few minutes. 

I don't have access to a server with announcments/storepage, so close this issue if the update works.

**Comment by pnotequalnp** [comment]
It seems to be working now. Thanks!
