### ISSUE TITLE
Random crash after connecting

### ISSUE THREAD

**Issue by pnotequalnp** [aquarial/discord-haskell#43]
This is frustratingly difficult to reproduce. I have multiple instances of the same minimal program connected to the same server, and it takes anywhere from a couple hours to a few days for one to crash. And they don't all crash at the same time. The message it gives is `GatewayExceptionUnexpected (InvalidSession False) "Response to Identify must be Ready"`. Using the following minimal program.
```haskell
import Data.Text ( Text )
import qualified Data.Text.IO as T

import Discord

test :: Text -> IO ()
test secret = do
 userFacingError <- runDiscord def
   { discordToken   = secret
   , discordOnStart = const $ putStrLn "Connected"
   , discordOnEnd   = putStrLn "Disconnected"
   }
 T.putStrLn userFacingError
```

**Comment by aquarial** [comment]
Have time to look at this now. Why do you have multiple instances of the same program? Do they use the same `token`?

> Clients are limited to 1 identify every 5 seconds; if they exceed this limit, the gateway will respond with an Opcode 9 Invalid Session
> https://discord.com/developers/docs/topics/gateway#identifying

Unlikely to help here I think, but does anything interesting show up if you set `discordOnLog :: T.Text -> IO ()` to print?

If you're curious, the error comes from
[here in the gateay](https://github.com/aquarial/discord-haskell/blob/master/src/Discord/Internal/Gateway/EventLoop.hs#L66). The code here is hard to read because of all the indirection.

**Comment by pnotequalnp** [comment]
Oh that makes some sense. I was running multiple just to try to get the crash. I do often have one "working" version running in the background while starting and stopping a dev version so perhaps that is the cause? What counts as a client in that restriction? Like any connections with the same token is just one client?

**Comment by aquarial** [comment]
Hmm. Good point on "what counts as a client". `Identify` is only sent at the very beginning of a connection, the server can't tell the difference between 5 clients that all start a connection at nearly the same time and 1 bot that re-connects 5 times. It's a limit on identifying, not running. 

Two version might be fine if they just listen to the gateway. I was picturing you running a flock of instances.

I'm not sure about what's going on here. Try printing logs for a few hours, and see if there's an underlying issue causing the reconnecting.

``haskell
test :: Text -> IO ()
test secret = do
 userFacingError <- runDiscord def
   { discordToken   = secret
   , discordOnLog   = T.putStrLn   -- print logs
   , discordOnStart = const $ putStrLn "Connected"
   , discordOnEnd   = putStrLn "Disconnected"
   }
 T.putStrLn userFacingError
``

**Comment by aquarial** [comment]
Is this still happening? Any new info here?

**Comment by aquarial** [comment]
Any new info? I'll check in every once in a while no pressure

**Comment by pnotequalnp** [comment]
Oh sorry, I haven't got a crash in a while now. Whatever the issue was seems to have been resolved.

**Comment by aquarial** [comment]
I guess no news can be good news.

Glad it's working
