### ISSUE TITLE
Non-blocking requests

### ISSUE THREAD

**Issue by Lemmih** [aquarial/discord-haskell#46]
Say I have a bot that both sends a message and adds a reaction. Right now, that requires two round trips. With non-blocking requests, it would only require a single round trip and thus have less latency.

**Comment by aquarial** [comment]
I think it will always require two trips. Reacting to a message requires knowing the id of the message. When we send a message, the server sends back the id, which we can then use to create the reaction. I think the http library `req` does http connection re-use, so it's not as inefficient as it could be

**Comment by aquarial** [comment]
Haskell is a green-thread language instead of an async/await language. For situations where you want two requests to happen on after another, while also doing other things use `forkIO` or something to start a new thread

Can you elaborate more on how `non-blocking requests` prevent http requests?

**Comment by Lemmih** [comment]
Imagine you want add two reactions to a message (or two separate messages). Right now you have to send the first request and wait for a response, then send the second request and wait for a response. If there was a non-blocking option, both requests could be sent without having to wait for a response. This can obviously be done with `forkIO` but then there's no guarantees about the ordering of requests.

More specifically, I'm thinking of something like `Discord.Internal.Rest.writeRestCall` that puts a request in the `chan` but doesn't immediately read the `MVar`. If it returned an action that read the `MVar` then many requests could be scheduled without having to first wait for the responses.

**Comment by aquarial** [comment]
Ohh, yeah that makes more sense. I was trying to figure out how non-blocking IO would help the library be faster ha.

Blocking IO is built into `discord-haskell` at a deer level than the interface. No matter how many `restCall`s are made across multiple threads at once, *all* the http requests are made in one loop, waiting for the last request to finish before starting the next. [Here's the big messy internal loop](https://github.com/aquarial/discord-haskell/blob/master/src/Discord/Internal/Rest/HTTP.hs#L42)

[Discord has rate-limits for libraries](https://discord.com/developers/docs/topics/rate-limits), so starting multiple http requests at the same time won't be faster, just more complicated

**Comment by aquarial** [comment]
It's been a while since I've thought about that loop haha, I was writing a whole comment about haskell concurrency before I remembered rate-limiting.

**Comment by Lemmih** [comment]
> Blocking IO is built into `discord-haskell` at a deer level than the interface. No matter how many `restCall`s are made across multiple threads at once, _all_ the http requests are made in one loop, waiting for the last request to finish before starting the next. [Here's the big messy internal loop](https://github.com/aquarial/discord-haskell/blob/master/src/Discord/Internal/Rest/HTTP.hs#L42)

Hm, right. And the HTTP library is strictly version 1.1 so we're not gonna get pipelining or multiplexing no matter what we do. I'll close this issue.
