### ISSUE TITLE
Include reactions in Message type

### ISSUE THREAD

**Issue by LukaHorvat** [aquarial/discord-haskell#56]
So I don't know if this is a newer change in the API but reactions are now returned when querying messages (even in bulk). The current type https://github.com/aquarial/discord-haskell/blob/master/src/Discord/Internal/Types/Channel.hs#L229 doesn't have a `reactions` field as documented in https://discord.com/developers/docs/resources/channel#message-object.

In my testing, the field is missing if there are no reactions.

**Comment by aquarial** [comment]
Interesting. Might be new, might have overlooked. Added `MessageReaction` to `Message` field, good note that the field is missing if no reactions.

It's got different fields than the `ReactionInfo` that comes with `MessageReactionAdd`, so I had to add a struct.

Potentially confusing that , but I'm not sure what else to do.

**Comment by LukaHorvat** [comment]
Cool! Thanks for the quick work!
