### ISSUE TITLE
Sending local files.

### ISSUE THREAD

**Issue by social-anthrax** [aquarial/discord-haskell#58]
I've been trying to send a message containing a local image, however, ` CreateMessageUploadFile` wants bytestring while if I open an image as bytestring it will be IO bytestring. Is there a way around this or is uploading the images to Imgur the simplest solution?

**Comment by aquarial** [comment]
Haskell feels weird to a lot of people who are not used to threading `IO a` in and out of contexts like this. The solution is to run the `readFile :: IO ByteString` action to bind a variable to the bytestring part, and then compose this with further actions that need the bytestring. Here's a short example

```haskell
import UnliftIO (liftIO)
import Discord
import Discord.Types
import qualified Discord.Requests as R

eventHandler :: Event -> DiscordHandler ()
eventHandler event = case event of
      MessageCreate m -> do
        regularstring <- liftIO (Bytestring.readFile "asd")
        _ <- restCall (R.CreateMessageUploadFile (messageChannel m) "text" regularstring)
        pure ()
      _ -> pure ()
```


The eventHandler is a `DiscordHandler ()`, which is a complicated type, but it can contain `IO a` actions as long as they are 'lifted' into it.

**Comment by social-anthrax** [comment]
That really helps, I was relying on performUnsafeIO, thank you!
