### ISSUE TITLE
Proposal: add slash commands

### ISSUE THREAD

**Issue by social-anthrax** [aquarial/discord-haskell#59]
Add slash commands as documented here:  [https://discord.com/developers/docs/interactions/slash-commands](https://discord.com/developers/docs/interactions/slash-commands)

**Comment by aquarial** [comment]
Interesting, new to me. 

I probably won't implement it, seems like a lot of work and I'm not that interested in it. Good to have an open issue about it for visibility

**Comment by social-anthrax** [comment]
Thank you for your consideration!

**Comment by aquarial** [comment]
Looks like it's only mandetory for large bots (75 servers). Still a good idea to implement at some point. 

> This change affects only verified bots, bots that are in 75 or more servers. Unverified bots in fewer than 75 servers are not affected at all.
> 
> On April 30th, we will remove verified apps' access to message content if they have not been approved for the Privileged Intent.
> 
> unverified apps and bots will continue to be able to access message content without restrictions, just like presence and guild member data.

https://support-dev.discord.com/hc/en-us/articles/4404772028055

**Comment by L0neGamer** [comment]
Social anthrax over there got started on this; I'm currently attempting to update it to the latest versions

https://github.com/social-anthrax/discord-haskell-slash-commands/commit/0e19e7666d88bad2211655fc5c2a4a62b1e16b49

**Comment by L0neGamer** [comment]
Update: there's a PR: https://github.com/aquarial/discord-haskell/pull/88

**Comment by aquarial** [comment]
Merged! Thanks SocialAnthrax and L0neGamer for putting in big work on this.
