### ISSUE TITLE
Bot loses activity after a while

### ISSUE THREAD

**Issue by travv0** [aquarial/discord-haskell#60]
This might be me misunderstanding how the Discord API works, but if I set an activity for a bot on startup, after a seemingly random amount of time the activity is unset in Discord.

**Comment by aquarial** [comment]
I dunno. [Docs don't say anything](https://discord.com/developers/docs/game-sdk/activities#updateactivity). How long on average? Ratelimit is 5times per 20 seconds, so they might expect you to just fork a loop-sleep-update if it lasts longer than a minute or so

**Comment by travv0** [comment]
It's usually a few hours before it gets unset. I'll take a look at how another library I've used handles it to see if it's doing anything special to preserve it.

**Comment by travv0** [comment]
You know what, I'm guessing I should've been setting the activity on the ready event instead of on bot startup. It probably gets cleared out on a temporary connection drop or something. I'll reopen this if that doesn't fix it, but I'm guessing it will.

**Comment by PixeLInc** [comment]
This can be caused by discord pushing code updates to the backend sometimes, it may not necessarily be the fault of the library.

Link to the old issue on the dapi docs repo: https://github.com/discord/discord-api-docs/issues/834

**Comment by travv0** [comment]
@PixeLInc Yeah I guess I should share in case someone else makes the same mistake I did, but setting it on startup was definitely the problem. Discord doesn't preserve the status when the bot reconnects.

**Comment by yutotakano** [comment]
Just stumbled across the same problem - is it the Ready event or the Resume event I should be looking out for? @travv0

**Comment by travv0** [comment]
I believe you want to set it in the Ready event, I think Resumed is only
sent as a response to the Resume command sent after a dropped connection.

**Comment by aquarial** [comment]
This feels like a detail the library should handle. I can save the last sent activity, and resend it on a re-connection. 

I will put a notice here when this is fixed.

**Comment by aquarial** [comment]
Should be fixed with 1.8.2 release. Open an issue if something comes up.

**Comment by travv0** [comment]
Great, thanks!
