### ISSUE TITLE
Add ActivityTypeCompeting?

### ISSUE THREAD

**Issue by yutotakano** [aquarial/discord-haskell#61]
Around last December, Discord introduced a new Activity type: `competing` that shows as "Competing in {name}".
The relevant documentation link is [here](https://discord.com/developers/docs/topics/gateway#activity-object-activity-types).

Would it be possible to implement this? I can see it becoming slightly complicated because the ID is 5, skipping over 4 (custom statuses, ignored for bots for now, although may be implemented later). This means `fromEnum` is not going to work or has to be altered slightly in https://github.com/aquarial/discord-haskell/blob/8e1988edaf9b39cc27f44c966e16a33d1ead7a35/src/Discord/Internal/Types/Gateway.hs#L148

**Comment by yutotakano** [comment]
Alternatively, you could also add ID4 (custom) like any other type. Discord completely ignores it anyway, and I think discord.py handles it like that - `client.change_presence()` blindly accepts all activity types and simply passes them on to Discord.

**Comment by aquarial** [comment]
Good issue, I will add this along with fixing https://github.com/aquarial/discord-haskell/issues/60 later today

**Comment by yutotakano** [comment]
I saw the latest commits and the update on Hackage, thank you very much!
