### ISSUE TITLE
4003 Not Authenticated after a few hours of uptime

### ISSUE THREAD

**Issue by yutotakano** [aquarial/discord-haskell#62]
Since updating the package to 1.8.2, our Discord bot experiences a 4003 connection error and goes offline after a few hours of uptime (usually around 3-4 hours, although this is from subjective experience).

The log prints the following:
```
GatewayExceptionConnection (CloseRequest 4003 "Not authenticated.") "Normal event loop close request"
```
![Image Version](https://i.imgur.com/r04XHyK.png)

The error is fully reproducible by leaving the the example ping-pong bot running for several hours.

I believe this is somehow related to the changes made when fixing #60. Considering this is quite a serious issue, I hope it is addressed quite soon - I've tried looking into the code, but networking is a little out of my scope and I couldn't exactly figure out what was causing the problem.

**Comment by aquarial** [comment]
I tested it for an hour or so, but it seemed stable. Worrying. I'll startup a pingpong again.

Docs say error code 4003 is sent when a library sends a user payload before sending the initial identification payload. https://discord.com/developers/docs/topics/opcodes-and-status-codes#gateway-gateway-close-event-codes

The `sendableLoop` (https://github.com/aquarial/discord-haskell/blob/master/src/Discord/Internal/Gateway/EventLoop.hs#L211) handles all sent payloads to the server. 

But `Identify` payload is sent way before the loop starts: https://github.com/aquarial/discord-haskell/blob/master/src/Discord/Internal/Gateway/EventLoop.hs#L58, and only when a new connection is created (which happens on startup, and when a reconnect fails).

hmm

**Comment by aquarial** [comment]
I've managed to reproduce this by starting up pingpong, disconnecting from wifi, waiting, then reconnecting. 

Quite serious

**Comment by aquarial** [comment]
Ah here we go: After a connection is lost, we send a `Resume` payload. This opens a new connection, and we start sending heartbeats and receiving acs. The change in #60 sends a user mesage here.

But if discord didn't store our session token, they send a pyaload 9 after receiving at least one heartbeat. Invalid Session: requesting us to re-identify. The userpayload arrives instead: giving us the 4003 error. 

This change exposed a flaw in my view of the eventloop logic: the `sendables` loop starts sending user payloads too quickly. there was always a (very small) possibility that a user payload sent at the exactly wrong time could cause this sort of crash.

Will fix this quickly now

**Comment by yutotakano** [comment]
Brilliant, thank you very much for the fast response! I'll be eagerly waiting for the fix :)

**Comment by aquarial** [comment]
Overconfidence on my part: the fix is not quick. 

Seems my reconnecting logic has been wrong from the start. Maybe.Need to do some more testing

**Comment by aquarial** [comment]
1.8.3 should fix this.

let me know if this or https://github.com/aquarial/discord-haskell/issues/60 happens again.

Had to review and test all my reconnecting logic, so it took way longer than I'd hoped
