### ISSUE TITLE
R in ping pong example

### ISSUE THREAD

**Issue by yutotakano** [aquarial/discord-haskell#65]
Thank you very much for the merge!

Commit 9a3492b41fc60b25b984d50ddd651fea1b3c496e unfortunately breaks the example ping-pong bot because the ADT is defined within the Discord.Requests module and not Types. Sorry for the confusing behaviour!

**Comment by aquarial** [comment]
! 

My bad, I didn't even test it out!

**Comment by aquarial** [comment]
Pushed 1.8.5

Thanks for the update
