### ISSUE TITLE
ChannelGuildCategory missing some major fields

### ISSUE THREAD

**Issue by yutotakano** [aquarial/discord-haskell#67]
The fields available in the current ChannelGuildCategory ADT are quite limited currently, as seen here: https://github.com/aquarial/discord-haskell/blob/ffe46538c508f498b7cd98367c2aec16ede7e8e7/src/Discord/Internal/Types/Channel.hs#L117-L120

This raises some inconsistencies, as `R.ModifyChannel` can modify positions and permission overwrites of both channels and categories, while it is only possible to retrieve them for normal channels through `R.GetChannel`.

[Discord's blog post on categories](https://support.discord.com/hc/en-us/articles/115001580171-Channel-Categories-101) highlights that categories can have permission overwrites and positions. More concretely, the rightmost column in the table in the [relevant docs](https://discord.com/developers/docs/resources/channel#modify-channel-json-params) show that all types of channels have `permission_overwrites` and `position`. Although this seems misleading since DM channels for one don't have those, I think we can be sure that category channels would have those fields.

Could these be implemented?

**Comment by aquarial** [comment]
Yeah this is a good idea. I can work on it

**Comment by aquarial** [comment]
Updated 1.8.6 with this change

Thanks for providing detailed report!
