### ISSUE TITLE
Bot crashes when confronted with a server containing a Stage

### ISSUE THREAD

**Issue by dixonary** [aquarial/discord-haskell#68]
Stages are a new Discord feature, and it is a new type of channel (id 13, I believe).

If there is such a channel in any server which the discord bot is in, it will not successfully handshake with the Discord API.

Two related lines get printed out.

One includes `response to Identify must be Ready` (it is the exact message mentioned in #43)
The other includes `GatewayExceptionEventParseError "Error in $: Error in $.channels[31]: Unknown channel type:13" "Normal event loop"` which is the exact message in #40 except replacing unknown channel id `5` with `13`.

The required fix is, I think, to add a new type of channel which represents Stages, with id 13, to the `discord-haskell` API client.

**Comment by aquarial** [comment]
Always new features from them.

I'll work on this sometime tonight.

Good report

**Comment by aquarial** [comment]
Try out 1.8.7, close the issue if it stops crashing. I'm not in a server with Storepage stuff, so I can't test this stuff directly. 

I also added a `ChannelUnknown` catchall, so future new channels shouldn't crash the bot.

**Comment by dixonary** [comment]
Unfortunately this doesn't quite work - the following error is thrown:

```
GatewayExceptionEventParseError "Error in $: Error in $.channels[6].topic: parsing Text failed, expected String, but encountered Null\" \"Normal event loop\""
```

I think that `Stage` channels do not have a topic. 

Also, you can create a `Stage` channel in your test server by setting it to be a Community server (which requires a couple of clicks, starting with the button below):

![image](https://user-images.githubusercontent.com/7945623/119259822-f51aea80-bbc7-11eb-9af8-3d368c482a75.png)

After that try to create a channel in the normal way and it will offer `Stage` as an option for the channel type :)

**Comment by aquarial** [comment]
Ah I see. I saw the [stage object](https://discord.com/developers/docs/resources/stage-instance#auto-closing-stage-instance-structure) and thought it required a topic.

Pushed the change to parse a null topic as an empty string.

**Comment by dixonary** [comment]
The latest commit does indeed work and the bot can handshake properly. :)

Thanks for the speedy fix!
