### ISSUE TITLE
best way to get message that was deleted?

### ISSUE THREAD

**Issue by shadowninja55** [aquarial/discord-haskell#74]
i'm trying to use the data of a message once it's deleted, but it's proving rather difficult. i don't see messages in the cache, and i also can't use `GetChannelMessage` with a deleted message. any ideas how i could build on the cache or make my own? thanks in advance.

**Comment by aquarial** [comment]
You're going to have to build your own cache. `Map MessageId Message`. You store the cache in state like https://github.com/aquarial/discord-haskell/issues/42.

Every `MessageCreate` you insert into the state, delete the older ones if the size is too big (1000 maybe?). Then in `MessageDelete` you check the map using Messageid

**Comment by shadowninja55** [comment]
> You're going to have to build your own cache. `Map MessageId Message`. You store the cache in state like #42.
> 
> Every `MessageCreate` you insert into the state, delete the older ones if the size is too big (1000 maybe?). Then in `MessageDelete` you check the map using Messageid

alright sounds good thanks for the help!
