### ISSUE TITLE
I can't use CreateMessageDetailed

### ISSUE THREAD

**Issue by spidermoy** [aquarial/discord-haskell#75]
Hi,

When I try:

```hs
responseWithDetailedMessage::Message->DiscordHandler ()
responseWithDetailedMessage m = do
  let opts :: R.MessageDetailedOpts
      opts = def {
        R.messageDetailedContent = "Hey @" <> (userName $ messageAuthor m),
        R.messageDetailedAllowedMentions =
          Just $ def {
            R.mentionUsers = True,
            R.mentionUserIds = [userId $ messageAuthor m]
          }
      }
  m' <- restCall $ R.CreateMessageDetailed (messageChannel m) opts
  liftIO $ print m'
```

the output is:

```
Left (RestCallErrorCode 400 "Bad Request" "{\"allowed_mentions\": [\"parse:[\\\"users\\\"] and users: [ids...] are mutually exclusive.\"]}")
```

Did I make a mistake?

Thanks.

**Comment by spidermoy** [comment]
https://discord.com/developers/docs/resources/channel#allowed-mentions-object

```
The parse field is mutually exclusive with the other fields. In the example below, we would ping users 123 and role 124, but not @everyone. Note that passing a Falsy value ([], null) into the "users" field does not trigger a validation error.
```

My solution was: 

```hs
void $ restCall $ R.CreateMessage channel_id $ "<@" user_id ">"
```

Any opinions?

**Comment by aquarial** [comment]
> The parse field is mutually exclusive with the other fields

Interesting, I didn't catch that part before. A fix for the specific `mutually exclusive` error is to suppress the parse-users field if  a list of user ids is provided (same for roles)

The content is a more ambiguous question. Seems like a ping to specific user needs to be in the form `<@id-num>. mentionUsers is on by `def`, so a detailed message with the `<@id-num>` would work without specifying any 'allowedMentions stuff'.

The purpose of detailedmessage allowedMentions is to protect against accidentally pinging people when sending input that a user has created.
