### ISSUE TITLE
GuildMemberAdd and GuildMemberRemove is not working

### ISSUE THREAD

**Issue by spidermoy** [aquarial/discord-haskell#76]
Hi, it's me, again.

When I tried this::

```hs
eventHandler::Event->DiscordHandler ()
eventHandler event = do
  liftIO $ putStrLn ""
  liftIO $ print event
  liftIO $ putStrLn ""
```

`GuildMemberAdd` and `GuildMemberRemove` was not detected :C

**Comment by spidermoy** [comment]
https://discord.com/developers/docs/topics/gateway#guild-member-add

```
If using Gateway Intents, the GUILD_MEMBERS intent will be required to receive this event.
```

Maybe that?

**Comment by aquarial** [comment]
Ahh yeah, looks like it. Thanks for debugging this stuff.

Haven't added gateway intents because they're optional for api v6, but they will become mandatory for v8. Maybe a big `data` struct with a field for [each intent](https://discord.com/developers/docs/topics/gateway#list-of-intents)? I think the default should be to listen to all of them, but let someone optimize their gateway comms if they want to.

Will look into this

**Comment by aquarial** [comment]
Still working on this, feeling the desire to rewrite a lot of eventloop because of [issue 70 stuff](https://github.com/aquarial/discord-haskell/issues/70) as well.

**Comment by spidermoy** [comment]
Thanks, man, you are so cool. 

Moreover, I will share in a few days with an idea about this issue: https://github.com/aquarial/discord-haskell/issues/59

Greetings from México again.

**Comment by aquarial** [comment]
Greetings again then! 


App is still using v6 of the api, so it looks like you can enable the member-presence intents using the developer pane at https://discord.com/developers/applications

I'll have to document this somewhere people can read. Perfect is the enemy of good here. 

![gateway intents](https://user-images.githubusercontent.com/37496339/130155242-581d8ca9-c053-423b-985d-53ce0b88a205.png)

**Comment by spidermoy** [comment]
Yes!!! It works!!!

This option was the solution:

![Screenshot_2021-08_20_11:56:32](https://user-images.githubusercontent.com/42991834/130268059-369a2ba0-cfeb-4fee-9e93-f19825969bb4.png)

Thanks again!

**Comment by aquarial** [comment]
Good to hear!

**Comment by aquarial** [comment]
The error message for using privileged intents now links to <https://github.com/aquarial/discord-haskell/blob/master/docs/intents.md> (it used to link here), so I'm going to close this issue. 

Thanks again  for the bug report
