### ISSUE TITLE
Missing color attribute for CreateEmbed

### ISSUE THREAD

**Issue by XanderDJ** [aquarial/discord-haskell#78]
It's currently not possible as far as I'm aware to input a color for the colored sidebox of an embed message. The color attribute is present in the Embed datatype but not in the CreateEmbed datatype which is the datatype that can be used to create an embedded message.

**Comment by aquarial** [comment]
Good point. I was delaying because I didn't know the best high level type to represent it, but a plain `Integer` type fits the usecase. Easier to represent in hex though, eg `16711680` vs `0xFF0000` for red

Pushed https://github.com/aquarial/discord-haskell/commit/0922fea89cba24a5b2c33a5e3a1fd31f4175c0cc, but haven't made a new release yet

**Comment by aquarial** [comment]
Released to `1.9.1`, close if you can build and confirm it

**Comment by XanderDJ** [comment]
I'll check rn

**Comment by XanderDJ** [comment]
Documentation seems to be broken on the hackage page, I don't know if this is because the release is early and some manual stuff still needs to take place. Release 1.9.1 compiled and works. Using f984ef as hex code. One issue with embeds is that they fail silently when certain fields don't have the right value. For example if you have an EmbedField that has an empty text value in either the name or the body then the messages will silently fail when people use a command that gets an embed with this in its body as a result. 

The same goes for the hex colours. If one were to give FFF984EF as the value of the color (thinking that the format is ARGB) then the bot will not show any errors or issues but all the messages with those codes will not get through to discord.

**Comment by aquarial** [comment]
> Documentation seems to be broken on the hackage page, I don't know if this is because the release is early and some manual stuff still needs to take place

It takes a while for hackage to compile the docs. There's some way to manually  upload them but I'm not sure exactly. Up now.

> One issue with embeds is that they fail silently when certain fields don't have the right value

This is a bit concerning. Should log the issue at least I guess.
