### ISSUE TITLE
Get a GatewayExceptionEventParseError

### ISSUE THREAD

**Issue by XanderDJ** [aquarial/discord-haskell#79]
When I restarted my bot it suddenly stopped working well. It starts up and then immediately crashes in the normal event loop. The following error is generated 'GatewayExceptionEventParseError "Error in $: Error in $: key \"region\" not found" "Normal event loop"' . I don't think I can give a good code example to reproduce the problem. I already tried using a different token but that wasn't the issue as I'm able to connect to the gateway without a bad auth error.

**Comment by XanderDJ** [comment]
It fixed itself. No Idea what the issue was.

**Comment by aquarial** [comment]
Weird. Parsing something from the gatway expecting a region? Maybe voice related. 

I've debated making parse errors non-fatal (just log it and continue instead of crashing). Usually a parse error means I need to update something, so good to be informed as fast as possible. IDK.

**Comment by aquarial** [comment]
Oh just saw https://github.com/aquarial/discord-haskell/pull/80 too

**Comment by aquarial** [comment]
Should be fixed by that PR.

Reopen if the issue is still here, or open a new one, etc.
