### ISSUE TITLE
Doesn't build with base 4.9.0.0

### ISSUE THREAD

**Issue by mniip** [aquarial/discord-haskell#8]
`Discord.Rest` imports `fromRight` from `Data.Either`.

The documentation for [Data.Either.fromRight](http://hackage.haskell.org/package/base/docs/Data-Either.html#v:fromRight) shows it's avilable `Since: 4.10.0.0`.

**Comment by aquarial** [comment]
Fixed by not importing `fromRight` in commit https://github.com/aquarial/discord-haskell/commit/08771f5ce2bca681c2e2844b0c6e5cbfc7c1ec01

**Comment by aquarial** [comment]
You can comment any other build errors here. Close this issue if there are no more errors building on base `4.9.0.0`.

I will close this issue if: I can verify myself there are no more build errors with base 4.9 `or` if there are no more comments within 1 week or so.

**Comment by mniip** [comment]
That seems to be the only missing function.

**Comment by hvr** [comment]
@aquarial fyi, I've fixed up the metadata of the affected releases

- before fixup: https://matrix.hackage.haskell.org/package/discord-haskell@1547678200
- after fixup: https://matrix.hackage.haskell.org/package/discord-haskell@1548691114

You can catch these kind issues quite easily before uploading to Hackage by enabling CI for your GitHub repository (e.g. https://github.com/haskell-CI/haskell-ci )
