### ISSUE TITLE
Reaction emoji name is sometimes null

### ISSUE THREAD

**Issue by yutotakano** [aquarial/discord-haskell#85]
Thanks as always for the library! Here was a small bug we experienced today.

## Bug

Our bot today experienced a rare library exception, due to a parse error in the message reaction field. Specifically, it appears that an reaction emoji `name` field was null which caused a parse error.

The log starts out like this:

```
RestCallErrorCode 400 "Library Stopped Working" "Parse Exception Error in $.reactions[1].emoji.name: parsing Text failed, expected String, but encountered Null for "{\"id\": \"921548226539192340\", \"type\": 0, \"content\": \"do they be d-t...
```

Further down the printed JSON, we could see the following:
```
...\"reactions\": [{\"emoji\": {\"id\": null, \"name\": \"\\ud83d\\ude0e\"}, \"count\": 1, \"me\": false}, {\"emoji\": {\"id\": \"785544906613325885\", \"name\": null}, \"count\": 1, \"me\": false}]}"
```

## Analysis

After some Googling, I found that the [Discord API docs does say the `name` field may be `null`](https://discord.com/developers/docs/resources/emoji#emoji-object-emoji-structure), but doesn't really specify when it would happen (apart from that it happens when it's in a reaction). It's a little peculiar because:

1. I found [a comment](https://github.com/discord/discord-api-docs/issues/812#issuecomment-554142833) on the discord-api-docs repository claiming MESSAGE_REACTION_REMOVE may trigger the field to be null, but the content seen in my log was a full Message object.
2. A full Message object is only sent on MESSAGE_CREATE or MESSAGE_UPDATE, but the message already was not edited (so not UPDATE), but it still had reactions (impossible for a newly created message).

Anyway, regardless of where it came from, I think it's safer to follow the docs and assume the name field may sometimes be `null`.

## Solution

I'd like to submit a PR to fix this. Am I correct in that only the following needs to change? (T.Text to Maybe T.Text, and `.:` to `.:?`)

https://github.com/aquarial/discord-haskell/blob/8572dcd0acd6a58e7ceebe589c5be179cef795c1/src/Discord/Internal/Types/Channel.hs#L262-L278

**Comment by aquarial** [comment]
> only the following needs to change?

Yep! Use `.:?` for `Maybe field`. Looking over it again just now, Emoji `id` should also be parsed with `.:?`.

> found some documentation online
> 
> 
> Visually, here are the message reaction emoji records you can expect to see:
> 
>  ```
> {
>    "id": null,
>    "name": "💯"
> }
> 
> {
>   "id": 347239456284572957,
>   "name": "customemote",
>   "animated": true
> }
> 
> {
>   "id": 347239456284572957,
>    "name": null
> }
> ```

Interesting, but also a bit annoying. Library users are going to see `id:: Maybe Int, name:: Maybe Text`, and not really know how to identify an emoji. But there is some structure hidden behind the optionals.  Something to put in docs I think. There's enough edge cases with all this stuff already, 

.

Open a merge request fixing this specifc thing and I'll be glad to merge. Docs are a later question

**Comment by yutotakano** [comment]
Upon review, it seems like use of `.:` is fine for both ID and Name. The Aeson docs say `.:` is to be used when the key is guaranteed to exist (even if null), and `.:?` to be used if the key may not exist. Going by this, it should be fine to use `.:` for both the Maybe emojiId and Maybe emojiName.

I'm making a PR very soon.

**Comment by aquarial** [comment]
Neat!
